//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResources.Strings.en_US {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyResources.Strings.en_US.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - global list of currently shared photos
        ///- overall view of air pollution over the Czech republic
        ///- visual improvements
        ///- some bug fixes 
        ///
        ///Selected photos are also available at Facebook page...
        ///
        ///Try our new project at www.resnap.it!.
        /// </summary>
        public static string _news {
            get {
                return ResourceManager.GetString("_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current.
        /// </summary>
        public static string AppCurrent {
            get {
                return ResourceManager.GetString("AppCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to history.
        /// </summary>
        public static string AppHistory {
            get {
                return ResourceManager.GetString("AppHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map.
        /// </summary>
        public static string AppMap {
            get {
                return ResourceManager.GetString("AppMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR POLLUTION.
        /// </summary>
        public static string AppNameUC {
            get {
                return ResourceManager.GetString("AppNameUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share a photo.
        /// </summary>
        public static string AppPhoto {
            get {
                return ResourceManager.GetString("AppPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photos.
        /// </summary>
        public static string AppPhotos {
            get {
                return ResourceManager.GetString("AppPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stations.
        /// </summary>
        public static string AppStations {
            get {
                return ResourceManager.GetString("AppStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo.
        /// </summary>
        public static string BtnCamera {
            get {
                return ResourceManager.GetString("BtnCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load photos.
        /// </summary>
        public static string BtnDetailsPhoto {
            get {
                return ResourceManager.GetString("BtnDetailsPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detail.
        /// </summary>
        public static string BtnDetailStation {
            get {
                return ResourceManager.GetString("BtnDetailStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to information.
        /// </summary>
        public static string BtnInformation {
            get {
                return ResourceManager.GetString("BtnInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nearest.
        /// </summary>
        public static string BtnNearestStation {
            get {
                return ResourceManager.GetString("BtnNearestStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review this app.
        /// </summary>
        public static string BtnReview {
            get {
                return ResourceManager.GetString("BtnReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send.
        /// </summary>
        public static string BtnSendPhoto {
            get {
                return ResourceManager.GetString("BtnSendPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset.
        /// </summary>
        public static string BtnSendReset {
            get {
                return ResourceManager.GetString("BtnSendReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort.
        /// </summary>
        public static string BtnSort {
            get {
                return ResourceManager.GetString("BtnSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zoom.
        /// </summary>
        public static string BtnZoom {
            get {
                return ResourceManager.GetString("BtnZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can use localization features.
        /// </summary>
        public static string CheckGPS {
            get {
                return ResourceManager.GetString("CheckGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use dynamic Live Tile.
        /// </summary>
        public static string CheckLiveTile {
            get {
                return ResourceManager.GetString("CheckLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto localize the nearest station.
        /// </summary>
        public static string CheckNearest {
            get {
                return ResourceManager.GetString("CheckNearest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included stations without quality.
        /// </summary>
        public static string CheckNearestWithoutQuality {
            get {
                return ResourceManager.GetString("CheckNearestWithoutQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suburban.
        /// </summary>
        public static string ClassAroundcity {
            get {
                return ResourceManager.GetString("ClassAroundcity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to industrial.
        /// </summary>
        public static string ClassIndustry {
            get {
                return ResourceManager.GetString("ClassIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urban.
        /// </summary>
        public static string ClassIntercity {
            get {
                return ResourceManager.GetString("ClassIntercity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to traffic.
        /// </summary>
        public static string ClassTraffic {
            get {
                return ResourceManager.GetString("ClassTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rural.
        /// </summary>
        public static string ClassVillage {
            get {
                return ResourceManager.GetString("ClassVillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbon monoxide (CO) is a colorless, odorless and poisonous gas produced by incomplete burning of carbon in fuels. When CO enters the bloodstream, it reduces the delivery of oxygen to the body&apos;s organs and tissues. Health threats are most serious for those who suffer from cardiovascular disease. Exposure to elevated CO levels can cause impairment of visual perception, manual dexterity, learning ability and performance of complex tasks.
        ///
        ///77% of the nationwide CO emissions are from transportation sources. T [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InfoCO {
            get {
                return ResourceManager.GetString("InfoCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitrogen dioxide (NO2) is a brownish, highly reactive gas that is present in all urban atmospheres. NO2 can irritate the lungs, cause bronchitis and pneumonia, and lower resistance to respiratory infections.
        ///
        ///The major mechanism for the formation of NO2 in the atmosphere is the oxidation of nitric oxide (NO), which is produced by most combustion processes..
        /// </summary>
        public static string InfoNO2 {
            get {
                return ResourceManager.GetString("InfoNO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ozone (O3) is the major component of smog. Although O3 in the upper atmosphere is beneficial because it shields the earth from the sun&apos;s harmful ultraviolet radiation, high concentrations of O3 at ground level are a major health and environmental concern. The reactivity of O3 causes health problems because it damages lung tissue, reduces lung function and sensitizes the lungs to other irritants. Scientific evidence indicates that ambient levels of O3 not only affect people with impaired respiratory systems, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InfoO3 {
            get {
                return ResourceManager.GetString("InfoO3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particulate matter (PM) is a mixture of particles that can adversely effect human health, damage materials and form atmospheric haze that degrades visibility. PM is usually divided up into different classes based on size, ranging from total suspended matter (TSP) to PM-10 (particles less than 10 microns in aerodynamic diameter) to PM-2.5 (particles less than 2.5 microns). In general, the smallest particles pose the highest human health risks. PM exposure can affect breathing, aggravate existing respiratory  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InfoPM10 {
            get {
                return ResourceManager.GetString("InfoPM10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the degree of pollution in your area is 5 or 6, then you should stay and reduce physical activity or sport in the outdoors, do not smoke, reduce car travelling, air the short and intense, increase the intake of vitamins and drink plenty of fluids..
        /// </summary>
        public static string InfoSmog {
            get {
                return ResourceManager.GetString("InfoSmog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High concentrations of sulfur dioxide (SO2) affect breathing and may aggravate existing respiratory and cardiovascular disease. Sensitive populations include asthmatics, individuals with bronchitis or emphysema, children and the elderly. SO2 is also a primary contributor to acid rain, which causes acidification of lakes and streams and can damage trees, crops, historic buildings and statues. In addition, sulfur compounds in the air contribute to visibility impairment in large parts of the country. This is e [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InfoSO2 {
            get {
                return ResourceManager.GetString("InfoSO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to used source: scorecard.goodguide.com.
        /// </summary>
        public static string InfoSource {
            get {
                return ResourceManager.GetString("InfoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is carbon monoxide (CO)?.
        /// </summary>
        public static string InfoTitleCO {
            get {
                return ResourceManager.GetString("InfoTitleCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is nitrogen dioxide (NO2)?.
        /// </summary>
        public static string InfoTitleNO2 {
            get {
                return ResourceManager.GetString("InfoTitleNO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is ozone (O3)?.
        /// </summary>
        public static string InfoTitleO3 {
            get {
                return ResourceManager.GetString("InfoTitleO3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is particulate matter (PM)?.
        /// </summary>
        public static string InfoTitlePM10 {
            get {
                return ResourceManager.GetString("InfoTitlePM10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is sulfur dioxide (SO2)?.
        /// </summary>
        public static string InfoTitleSO2 {
            get {
                return ResourceManager.GetString("InfoTitleSO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is smog....
        /// </summary>
        public static string InfoWhatToDo {
            get {
                return ResourceManager.GetString("InfoWhatToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during data processing, please contact the author of application!.
        /// </summary>
        public static string MsgDataError {
            get {
                return ResourceManager.GetString("MsgDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to download current data. App tries to use last downloaded data!.
        /// </summary>
        public static string MsgDownloadError {
            get {
                return ResourceManager.GetString("MsgDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The localization features are disabled!.
        /// </summary>
        public static string MsgGPSDisabled {
            get {
                return ResourceManager.GetString("MsgGPSDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to obtain your location!.
        /// </summary>
        public static string MsgGPSUnavailable {
            get {
                return ResourceManager.GetString("MsgGPSUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is unable to obtain historical data of this station!.
        /// </summary>
        public static string MsgHistoryError {
            get {
                return ResourceManager.GetString("MsgHistoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data for visualization! App is not fully functional!.
        /// </summary>
        public static string MsgNoData {
            get {
                return ResourceManager.GetString("MsgNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to very good.
        /// </summary>
        public static string QualityState1 {
            get {
                return ResourceManager.GetString("QualityState1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to good.
        /// </summary>
        public static string QualityState2 {
            get {
                return ResourceManager.GetString("QualityState2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fair.
        /// </summary>
        public static string QualityState3 {
            get {
                return ResourceManager.GetString("QualityState3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suitable.
        /// </summary>
        public static string QualityState4 {
            get {
                return ResourceManager.GetString("QualityState4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poor.
        /// </summary>
        public static string QualityState5 {
            get {
                return ResourceManager.GetString("QualityState5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to very poor.
        /// </summary>
        public static string QualityState6 {
            get {
                return ResourceManager.GetString("QualityState6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not measure.
        /// </summary>
        public static string QualityState7 {
            get {
                return ResourceManager.GetString("QualityState7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missed data.
        /// </summary>
        public static string QualityState8 {
            get {
                return ResourceManager.GetString("QualityState8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Capital Prague.
        /// </summary>
        public static string RegionA {
            get {
                return ResourceManager.GetString("RegionA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southern Moravian Region.
        /// </summary>
        public static string RegionB {
            get {
                return ResourceManager.GetString("RegionB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Bohemian Region.
        /// </summary>
        public static string RegionC {
            get {
                return ResourceManager.GetString("RegionC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pardubice Region.
        /// </summary>
        public static string RegionE {
            get {
                return ResourceManager.GetString("RegionE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hradec Králové Region.
        /// </summary>
        public static string RegionH {
            get {
                return ResourceManager.GetString("RegionH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vysočina Region.
        /// </summary>
        public static string RegionJ {
            get {
                return ResourceManager.GetString("RegionJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karlovy Vary Region.
        /// </summary>
        public static string RegionK {
            get {
                return ResourceManager.GetString("RegionK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberec Region.
        /// </summary>
        public static string RegionL {
            get {
                return ResourceManager.GetString("RegionL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olomouc Region.
        /// </summary>
        public static string RegionM {
            get {
                return ResourceManager.GetString("RegionM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plzeň Region.
        /// </summary>
        public static string RegionP {
            get {
                return ResourceManager.GetString("RegionP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Bohemia Region.
        /// </summary>
        public static string RegionS {
            get {
                return ResourceManager.GetString("RegionS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moravian-Silesian Region.
        /// </summary>
        public static string RegionT {
            get {
                return ResourceManager.GetString("RegionT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ústí Region.
        /// </summary>
        public static string RegionU {
            get {
                return ResourceManager.GetString("RegionU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zlín Region.
        /// </summary>
        public static string RegionZ {
            get {
                return ResourceManager.GetString("RegionZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select current station manually.
        /// </summary>
        public static string SelectStation {
            get {
                return ResourceManager.GetString("SelectStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App that offers rapid and easy to use detection of air quality and pollution. It can be focused on your location or the set of all stations in the Czech republic. Data source: www.chmi.cz.
        /// </summary>
        public static string TextAbout {
            get {
                return ResourceManager.GetString("TextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings.
        /// </summary>
        public static string TextAppSetting {
            get {
                return ResourceManager.GetString("TextAppSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application provides the ability to share photos describing the subjective state of the air in your area. Take a photo, rate a condition that expresses, add comments and send it. Each photo is stored in relation to the nearest measuring station..
        /// </summary>
        public static string TextCameraAbout {
            get {
                return ResourceManager.GetString("TextCameraAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After the approval, the shared photos (and additional information) are shown at the detailed page of a given station. It is always displayed only a limited number of last photos. Selected photos will also be published on the Facebook page of the author of this application..
        /// </summary>
        public static string TextCameraShare {
            get {
                return ResourceManager.GetString("TextCameraShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos should capture both positive and negative states of the air. They should contain general scenery mainly, no human faces or other private content. Photos or comments must not be offensive, vulgar, etc., and must respond to the nature and purpose of the topic described. All submitted photos are approved before publication..
        /// </summary>
        public static string TextCameraSubmitInfo {
            get {
                return ResourceManager.GetString("TextCameraSubmitInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By submitting photos (and additional information) you consent to the free use of them by the authors of this application. Application author reserves the right not to publish photos (or additional information) and accepts no responsibility for the content of the submitted photos. For taking photos and sharing it is necessary to use location-based services and internet data access. The application does not use any direct personally identifiable information of user or phone, but only anonymised Live ID accoun [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TextCameraTerms {
            get {
                return ResourceManager.GetString("TextCameraTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current station.
        /// </summary>
        public static string TextCurrentStation {
            get {
                return ResourceManager.GetString("TextCurrentStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data source: ČHMI (www.chmi.cz) for Czech Republic.
        /// </summary>
        public static string TextDataSource {
            get {
                return ResourceManager.GetString("TextDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can see last approved photos shared by other users of this application. These photos are related to a given station. You can share the photo too, start at the current station page..
        /// </summary>
        public static string TextDetailsPhoto {
            get {
                return ResourceManager.GetString("TextDetailsPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data downloading ....
        /// </summary>
        public static string TextDownloading {
            get {
                return ResourceManager.GetString("TextDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization is disabled.
        /// </summary>
        public static string TextGPSDisabled {
            get {
                return ResourceManager.GetString("TextGPSDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts of values ​​of individual elements in the last {0} days.
        /// </summary>
        public static string TextHistoryElements {
            get {
                return ResourceManager.GetString("TextHistoryElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The frequency of air quality index for the last {0} days.
        /// </summary>
        public static string TextHistoryQuality {
            get {
                return ResourceManager.GetString("TextHistoryQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to take a photo.
        /// </summary>
        public static string TextInfoCam {
            get {
                return ResourceManager.GetString("TextInfoCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App language.
        /// </summary>
        public static string TextLanguage {
            get {
                return ResourceManager.GetString("TextLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App should be restarted. App name will be still based on system language!.
        /// </summary>
        public static string TextLanguageInfo {
            get {
                return ResourceManager.GetString("TextLanguageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to based on system.
        /// </summary>
        public static string TextLanguageSystem {
            get {
                return ResourceManager.GetString("TextLanguageSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last photo:.
        /// </summary>
        public static string TextLastPhoto {
            get {
                return ResourceManager.GetString("TextLastPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The live tile is updated at intervals of approx. 30 minutes. If the tile is not updated, you should restart this application. The data connection is necessary for automatic tile update! Only limited amount of background agents can be activated within the system, that is important requirement for tile updating process, see System Settings - Applications..
        /// </summary>
        public static string TextLiveTile {
            get {
                return ResourceManager.GetString("TextLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading ....
        /// </summary>
        public static string TextLoading {
            get {
                return ResourceManager.GetString("TextLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new:.
        /// </summary>
        public static string TextNew {
            get {
                return ResourceManager.GetString("TextNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no data.
        /// </summary>
        public static string TextNoData {
            get {
                return ResourceManager.GetString("TextNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note or comment.
        /// </summary>
        public static string TextNote {
            get {
                return ResourceManager.GetString("TextNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data processing ....
        /// </summary>
        public static string TextParsing {
            get {
                return ResourceManager.GetString("TextParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to author.
        /// </summary>
        public static string TextPublisher {
            get {
                return ResourceManager.GetString("TextPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel free to review this app and give us the feedback and other ideas for future versions..
        /// </summary>
        public static string TextReview {
            get {
                return ResourceManager.GetString("TextReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your photo sent successfully. Thank you..
        /// </summary>
        public static string TextSendDone {
            get {
                return ResourceManager.GetString("TextSendDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error during the sharing your photo!.
        /// </summary>
        public static string TextSendError {
            get {
                return ResourceManager.GetString("TextSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing a photo.
        /// </summary>
        public static string TextSendImageTitle {
            get {
                return ResourceManager.GetString("TextSendImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a suitable smile according to the photo.
        /// </summary>
        public static string TextSendSmileSelect {
            get {
                return ResourceManager.GetString("TextSendSmileSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is unable to share a photo. The location features and internet connectivity are crucial for it!.
        /// </summary>
        public static string TextSendUnable {
            get {
                return ResourceManager.GetString("TextSendUnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to send a photo without note?.
        /// </summary>
        public static string TextSendWithoutNote {
            get {
                return ResourceManager.GetString("TextSendWithoutNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUI updating ....
        /// </summary>
        public static string TextStarting {
            get {
                return ResourceManager.GetString("TextStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case of problems with this app, please mail to info@garvis.cz!.
        /// </summary>
        public static string TextSupport {
            get {
                return ResourceManager.GetString("TextSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background agents for this application have been disabled by the user..
        /// </summary>
        public static string TextTaskDisabled {
            get {
                return ResourceManager.GetString("TextTaskDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to register background agent for this application. The tile is not live!.
        /// </summary>
        public static string TextTaskError {
            get {
                return ResourceManager.GetString("TextTaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update failed at {0}!.
        /// </summary>
        public static string TextTaskFailed {
            get {
                return ResourceManager.GetString("TextTaskFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information on automatic Live Tile updating.
        /// </summary>
        public static string TextTaskInfo {
            get {
                return ResourceManager.GetString("TextTaskInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update was OK at {0}.
        /// </summary>
        public static string TextTaskOK {
            get {
                return ResourceManager.GetString("TextTaskOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the proper operation the App requires a data connection and access to data provider (www.chmi.cz). The localization of your phone can be used to determine the nearest station. All phone location information is used only for internal functionality and is not further processed in any manner or distributed outside of the phone..
        /// </summary>
        public static string TextTerms {
            get {
                return ResourceManager.GetString("TextTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updated:.
        /// </summary>
        public static string TextUpdateTime {
            get {
                return ResourceManager.GetString("TextUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string TextVersion {
            get {
                return ResourceManager.GetString("TextVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is new?.
        /// </summary>
        public static string WhatIsNew {
            get {
                return ResourceManager.GetString("WhatIsNew", resourceCulture);
            }
        }
    }
}
